### ISSUE TITLE
Option to disable console spam

### ISSUE THREAD

**Issue by NotJustPizza** [VirtualByte/MineResetLite#1]
```
[10:16:14 INFO]: ?f[?4MRL?f] ?c2 ?dhas been reset automatically!
[10:16:14 INFO]: ?f[?4MRL?f] ?c1 ?dhas been reset automatically!
[10:16:14 INFO]: ?f[?4MRL?f] ?c3 ?dhas been reset automatically!
[10:16:14 INFO]: ?f[?4MRL?f] ?c4 ?dhas been reset automatically!
[10:31:16 INFO]: ?f[?4MRL?f] ?c2 ?dhas been reset automatically!
[10:31:16 INFO]: ?f[?4MRL?f] ?c1 ?dhas been reset automatically!
[10:31:16 INFO]: ?f[?4MRL?f] ?c3 ?dhas been reset automatically!
[10:31:16 INFO]: ?f[?4MRL?f] ?c4 ?dhas been reset automatically!
[10:46:19 INFO]: ?f[?4MRL?f] ?c2 ?dhas been reset automatically!
[10:46:19 INFO]: ?f[?4MRL?f] ?c1 ?dhas been reset automatically!
[10:46:19 INFO]: ?f[?4MRL?f] ?c3 ?dhas been reset automatically!
[10:46:19 INFO]: ?f[?4MRL?f] ?c4 ?dhas been reset automatically!
```

MRL messages fill console and logs...

**Comment by VirtualByte** [comment]
I'll have it done by tomorrow.

**Comment by SlimaKCoder** [comment]
Ok, i will wait :)

**Comment by SlimaKCoder** [comment]
"I'll have it done by tomorrow." commented 3 days ago xD

**Comment by NotJustPizza** [comment]
"I'll have it done by tomorrow." commented 7 days ago -,o

**Comment by VirtualByte** [comment]
I forgot - I'll do it now.

**Comment by VirtualByte** [comment]
Done. Edit config.yml and put in this to disable logging to console:

consoleLogMineReset: false

**Comment by NotJustPizza** [comment]
Compiled plugin dont work...

When server starting:

```
[19:47:20 INFO]: [MineResetLite] Enabling MineResetLite v0.4.5
[19:47:20 INFO]: [MineResetLite] Loading mine from file 'Kopalnia_2.mine.yml'...
[19:47:20 INFO]: [MineResetLite] Loading mine from file 'Drzewo_1.mine.yml'...
[19:47:20 INFO]: [MineResetLite] Loading mine from file 'Kopalnia_1.mine.yml'...
[19:47:20 INFO]: [MineResetLite] Loading mine from file 'Kopalnia_3.mine.yml'...
[19:47:20 INFO]: [MineResetLite] Loading mine from file 'Kopalnia_4.mine.yml'...
[19:47:20 ERROR]: Error occurred while enabling MineResetLite v0.4.5 (Is it up to date?)
java.lang.NullPointerException
        at com.koletar.jj.mineresetlite.MineResetLite.onEnable(MineResetLite.java:139) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-44c59bf-8f0f4ed]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-44c59bf-8f0f4ed]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-44c59bf-8f0f4ed]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:356) [spigot.jar:git-Spigot-44c59bf-8f0f4ed]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:316) [spigot.jar:git-Spigot-44c59bf-8f0f4ed]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:418) [spigot.jar:git-Spigot-44c59bf-8f0f4ed]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:382) [spigot.jar:git-Spigot-44c59bf-8f0f4ed]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:337) [spigot.jar:git-Spigot-44c59bf-8f0f4ed]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:256) [spigot.jar:git-Spigot-44c59bf-8f0f4ed]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:528) [spigot.jar:git-Spigot-44c59bf-8f0f4ed]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_80]
```

When reloading by PlugMan:

```
[19:49:56 INFO]: [MineResetLite] Disabling MineResetLite v0.4.5
[19:49:56 INFO]: [MineResetLite] MineResetLite disabled
[19:49:56 INFO]: [MineResetLite] Enabling MineResetLite v0.4.5
[19:49:56 INFO]: [MineResetLite] Loading mine from file 'Kopalnia_2.mine.yml'...
[19:49:56 INFO]: [MineResetLite] Loading mine from file 'Drzewo_1.mine.yml'...
[19:49:56 INFO]: [MineResetLite] Loading mine from file 'Kopalnia_1.mine.yml'...
[19:49:56 INFO]: [MineResetLite] Loading mine from file 'Kopalnia_3.mine.yml'...
[19:49:56 INFO]: [MineResetLite] Loading mine from file 'Kopalnia_4.mine.yml'...
[19:49:56 ERROR]: Error occurred while enabling MineResetLite v0.4.5 (Is it up to date?)
java.lang.NullPointerException
        at com.koletar.jj.mineresetlite.MineResetLite.onEnable(MineResetLite.java:139) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-44c59bf-8f0f4ed]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-44c59bf-8f0f4ed]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-44c59bf-8f0f4ed]
        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:286) [PlugMan%20v.2.0.4.jar:?]
        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:239) [PlugMan%20v.2.0.4.jar:?]
        at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:300) [PlugMan%20v.2.0.4.jar:?]
        at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122) [PlugMan%20v.2.0.4.jar:?]
        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:104) [PlugMan%20v.2.0.4.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot.jar:git-Spigot-44c59bf-8f0f4ed]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-44c59bf-8f0f4ed]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:642) [spigot.jar:git-Spigot-44c59bf-8f0f4ed]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:628) [spigot.jar:git-Spigot-44c59bf-8f0f4ed]
        at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:404) [spigot.jar:git-Spigot-44c59bf-8f0f4ed]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:368) [spigot.jar:git-Spigot-44c59bf-8f0f4ed]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot.jar:git-Spigot-44c59bf-8f0f4ed]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot.jar:git-Spigot-44c59bf-8f0f4ed]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_80]
```

Server version:

```
[19:53:42 INFO]: This server is running CraftBukkit version git-Spigot-44c59bf-8f0f4ed (MC: 1.8.7) (Implementing API version 1.8.7-R0.1-SNAPSHOT)
```

**Comment by NotJustPizza** [comment]
@Edit

I ignored that error and plugin seems to work o.O

**Comment by NotJustPizza** [comment]
@Edit

```
[14:09:01 INFO]: ?f[?4MRL?f] ?cKopalnia_2 ?dwill reset in ?55 ?dminute(s)!
[14:09:01 INFO]: ?f[?4MRL?f] ?cKopalnia_1 ?dwill reset in ?55 ?dminute(s)!
[14:09:01 INFO]: ?f[?4MRL?f] ?cKopalnia_3 ?dwill reset in ?55 ?dminute(s)!
[14:09:01 INFO]: ?f[?4MRL?f] ?cKopalnia_4 ?dwill reset in ?55 ?dminute(s)!
[14:13:02 INFO]: ?f[?4MRL?f] ?cKopalnia_2 ?dwill reset in ?51 ?dminute(s)!
[14:13:02 INFO]: ?f[?4MRL?f] ?cKopalnia_1 ?dwill reset in ?51 ?dminute(s)!
[14:13:02 INFO]: ?f[?4MRL?f] ?cKopalnia_3 ?dwill reset in ?51 ?dminute(s)!
[14:13:02 INFO]: ?f[?4MRL?f] ?cKopalnia_4 ?dwill reset in ?51 ?dminute(s)!
[14:14:03 INFO]: ?f[?4MRL?f] ?cKopalnia_2 ?dhas been reset automatically!
[14:14:03 INFO]: ?f[?4MRL?f] ?cKopalnia_1 ?dhas been reset automatically!
[14:14:03 INFO]: ?f[?4MRL?f] ?cKopalnia_3 ?dhas been reset automatically!
[14:14:03 INFO]: ?f[?4MRL?f] ?cKopalnia_4 ?dhas been reset automatically!
```

Plugin still spam console ;/

**Comment by VirtualByte** [comment]
Are you sure you have set this in config.yml?

consoleLogMineReset: false

**Comment by NotJustPizza** [comment]
``` yaml
# MineResetLite Configuration File
# If you have multiple worlds, and wish for only the worlds in which your mine resides to receive
# reset notifications, and automatic reset warnings, set this to true.
broadcast-in-world-only: false
# If you only want players nearby the mines to receive reset notifications,
# and automatic reset warnings, set this to true. Note: Currently only broadcasts to players in the mine
broadcast-nearby-only: true
# When true, this config option enables update alerts. I do not send any extra information along when 
# checking, and query a static file hosted on Dropbox. 
check-for-updates: true
# MineResetLite supports multiple languages. Indicate the language to be used here.
# Languages available at the time this config was generated: Danish (thanks Beijiru), Spanish (thanks enetocs), Portuguese (thanks FelipeMarques14), Italian (thanks JoLong)
# Use the following values for these languages: English: 'en', Danish: 'da', Spanish: 'es', Portuguese: 'pt', Italian: 'it', French: 'fr', Dutch: 'nl', Polish: 'pl'
# A fully up-to-date list of languages is available at http://dev.bukkit.org/server-mods/mineresetlite/pages/internationalization/
locale: en

#added
consoleLogMineReset: false
```

**Comment by NotJustPizza** [comment]
@VirtualByte are you alive?

**Comment by VirtualByte** [comment]
Sorry end of year exams.

**Comment by VirtualByte** [comment]
Pushed.

**Comment by SlimaKCoder** [comment]
```
[19:51:44 INFO]: ?f[?4MRL?f] ?cKopalnia_2 ?dwill reset in ?55 ?dminute(s)!
[19:51:44 INFO]: ?f[?4MRL?f] ?cKopalnia_1 ?dwill reset in ?55 ?dminute(s)!
[19:51:44 INFO]: ?f[?4MRL?f] ?cKopalnia_3 ?dwill reset in ?55 ?dminute(s)!
[19:51:44 INFO]: ?f[?4MRL?f] ?cKopalnia_4 ?dwill reset in ?55 ?dminute(s)!
```

**Comment by NotJustPizza** [comment]
Console spam stopped ;) Thx ;) But anyway i still have startup error ;/

```
[20:02:29 ERROR]: Error occurred while enabling MineResetLite v0.4.5 (Is it up to date?)
java.lang.NullPointerException
        at com.koletar.jj.mineresetlite.MineResetLite.onEnable(MineResetLite.java:141) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-f928e7a-d432434]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-f928e7a-d432434]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-f928e7a-d432434]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:356) [spigot.jar:git-Spigot-f928e7a-d432434]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:316) [spigot.jar:git-Spigot-f928e7a-d432434]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:418) [spigot.jar:git-Spigot-f928e7a-d432434]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:382) [spigot.jar:git-Spigot-f928e7a-d432434]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:337) [spigot.jar:git-Spigot-f928e7a-d432434]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:256) [spigot.jar:git-Spigot-f928e7a-d432434]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:528) [spigot.jar:git-Spigot-f928e7a-d432434]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_80]
```

**Comment by VirtualByte** [comment]
Fixed.

**Comment by NotJustPizza** [comment]
All good ;)

```
[23:52:00 INFO]: [MineResetLite] Enabling MineResetLite v0.4.5
[23:52:00 INFO]: [MineResetLite] Loading mine from file 'Kopalnia_2.mine.yml'...
[23:52:00 INFO]: [MineResetLite] Loading mine from file 'Drzewo_1.mine.yml'...
[23:52:00 INFO]: [MineResetLite] Loading mine from file 'Kopalnia_1.mine.yml'...
[23:52:00 INFO]: [MineResetLite] Loading mine from file 'Kopalnia_3.mine.yml'...
[23:52:00 INFO]: [MineResetLite] Loading mine from file 'Kopalnia_4.mine.yml'...
[23:52:00 INFO]: [MineResetLite] MineResetLite version 0.4.5 enabled!
```
